# Generated by Django 4.2.4 on 2023-09-13 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('rate', models.IntegerField()),
                ('person', models.IntegerField()),
                ('link', models.URLField(blank=True, max_length=700, null=True)),
                ('show', models.URLField(blank=True, max_length=700, null=True)),
                ('post', models.URLField(blank=True, max_length=700, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('star', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('imageLink', models.URLField(max_length=400)),
                ('profileLink', models.URLField(max_length=400)),
                ('comapany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
