# Generated by Django 4.0 on 2023-09-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_id_alter_reviewer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='link',
        ),
        migrations.RemoveField(
            model_name='company',
            name='post',
        ),
        migrations.RemoveField(
            model_name='company',
            name='show',
        ),
    ]
