# Generated by Django 4.0 on 2023-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_company_link_remove_company_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
