# Generated by Django 4.0 on 2023-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_company_created_at_remove_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rate',
            field=models.FloatField(),
        ),
    ]
